### ISSUE TITLE
Production ready bootloader

### ISSUE THREAD

**Issue by JOSE-Sendance** [sendance/nrf52_bootloader#2]
**Current situation**
The bootloader only works in debug mode, does just reset in release mode. No custom task in pio is available to do production download of firmware (app+bl+sd)

**Goal**
Have a production ready bootloader

**Execution**
- [x] Find out why non-debug mode is not working in bootloader
- [x] Add custom task to grid-firmware to download everything (app+bl+sd) in one package, or generate full package

**Results**
Bootloader is working in production package (app+bl+sd)
The crc check works if the bootloader settings are generated from the correct firmware. (Is done in the grid-firmware production task automatically)
USDB is deactivated completely (no USB serial DFU) for the release bootloader, so that Logging can be disabled (seems to be some SDK problem)
The writing of the UICR registers can be done to protect the uC  from JTAG read/write access.

**Comment by JOSE-Sendance** [comment]
Release version of bootloader is not working because of the flag NRF_DFU_DEBUG_VERSION which is not defined in release.
The problem on the one hand is that the current error handler just resets the uC, which should not happen.
The crc check of the application in the bootloader fails if it is compiled in release version => which makes sense
If the bootloader settings is generated from the correct firmware image, the crc is ok and the application starts. This needs to be implemented into a custom pio task.

**Comment by JOSE-Sendance** [comment]
CFLAGS += -DNRF_BL_DEBUG_PORT_DISABLE # does not seem to work, still able to readreads with nrfjprog
This is probably done in application or UICR otherwise written

**Comment by JOSE-Sendance** [comment]
The bootloader in release mode (without DEBUG=1) does boot the application if everthing is set correctly, but the dfu does not work. 

CFLAGS += -DDEBUG_NRF # 
CFLAGS += -DBOOTLOADER_DEBUG

these 2 flags need to be set that it works, but it is not DEBUG mode then anymore

**Comment by JOSE-Sendance** [comment]
Asked kaidyth if he has any clues why this could be.
Probably for now it would be ok to just let these flags enabled. if someone has access to the JTAG it is "over" anyway, and the bootloader does not really print out any sensitive information anyway.

**Comment by CSC-Sendance** [comment]
debug flags may stay as current limitation. task should be finished within two weeks (no need to move)

**Comment by JOSE-Sendance** [comment]
It seems to be a problem in combination of Logging and USBD being activated in the wrong order.
USBD is deactivated completely then logging can also be disabled.
The DFU over USB in NOT working then, but was not desired anyway.

https://devzone.nordicsemi.com/f/nordic-q-a/74465/usb-dfu-combined-with-buttonless-ble-dfu

**Comment by CSC-Sendance** [comment]
TODOs: 

- [x]  add LICENSE files of framework + bootloader
- [x] add build/flash instructions to README (firmware + bootloader)
